services:
    ngs_home.locale_listener:
        class: NGS\HomeBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }