imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: NGS\UserBundle\Entity\User

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en_US

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: [NGSHomeBundle, NGSUserBundle, FOSUserBundle, NGSContentBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
    assets:
    #     bootstrap_datepicker_css:
    #         inputs:
    #             - '../vendor/eternicode/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css'
        common_css:
            inputs:
                - '../vendor/twitter/bootstrap/dist/css/bootstrap.min.css'
        jquery_js:
            inputs:
                - '../vendor/components/jquery/jquery.min.js'
        bootstrap_js:
            inputs:
                - '../vendor/twitter/bootstrap/dist/js/bootstrap.min.js'
    #     bootstrap_datepicker_js:
    #         inputs:
    #             - '../vendor/eternicode/bootstrap-datepicker/js/bootstrap-datepicker.js'
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

a2lix_translation_form:
    locale_provider: default
    locales: [en_US, km_KH]
    default_locale: en_US
    required_locales: []
    manager_registry: doctrine
    # templating: "NGSContentBundle:Content:a2lix_translation.html.twig"

ivory_ck_editor:
    js_path: "/bundles/ivoryckeditor/ckeditor.js"
    default_config: default
    configs:
        default:
            toolbar:
                    - {name: 'styles', items: ['Styles', 'Font', 'FontSize'] }
                    - {name: 'basicstyles', items: ['Bold', 'Italic', 'Underline']}
                    - {name: 'colors', items: ['TextColor']}
                    - {name: 'paragraph', items: ['JustifyLeft', 'JustifyCenter', 'JustifyRight','NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-']}