ngs_content:
    resource: "@NGSContentBundle/Resources/config/routing.yml"
    prefix:   /

ngs_user:
    resource: "@NGSUserBundle/Resources/config/routing.yml"
    prefix:   /

ngs_home:
    resource: "@NGSHomeBundle/Resources/config/routing.yml"
    prefix:   /

# ngs_admin:
#     resource: "@NGSContentBundle/Resources/config/routing.yml"
#     prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mremi_contact_form:
    resource: "@MremiContactBundle/Resources/config/routing.xml"
