ngs_content_about:
    path:     /about
    defaults: { _controller: NGSContentBundle:About:index }

admin_dashboard:
    path:     /dashboard
    defaults: { _controller: NGSContentBundle:Admin/Dashboard:index }

admin_articles:
    path:     /articles
    defaults: { _controller: NGSContentBundle:Admin/Articles:index }

admin_article_new:
    path:     /article/new
    defaults: { _controller: NGSContentBundle:Admin/Articles:new }

admin_article_edit:
    path:     /article/{id}/edit
    defaults: { _controller: NGSContentBundle:Admin/Articles:edit }

admin_article_delete:
    path:     /article/{id}/delete
    defaults: { _controller: NGSContentBundle:Admin/Articles:delete }

admin_announcement:
    path:     /announcement
    defaults: { _controller: NGSContentBundle:Admin/Announcement:index }
admin_announcement_new:
    path:     /announcement/new
    defaults: { _controller: NGSContentBundle:Admin/Announcement:new }

admin_announcement_edit:
    path:     /announcement/{id}/edit
    defaults: { _controller: NGSContentBundle:Admin/Announcement:edit }

admin_announcement_delete:
    path:     /announcement/{id}/delete
    defaults: { _controller: NGSContentBundle:Admin/Announcement:delete }

admin_event:
    path:     /event
    defaults: { _controller: NGSContentBundle:Admin/Event:index }
admin_event_new:
    path:     /event/new
    defaults: { _controller: NGSContentBundle:Admin/Event:new }

admin_event_edit:
    path:     /event/{id}/edit
    defaults: { _controller: NGSContentBundle:Admin/Event:edit }

admin_event_delete:
    path:     /event/{id}/delete
    defaults: { _controller: NGSContentBundle:Admin/Event:delete }

admin_library:
    path:     /library
    defaults: { _controller: NGSContentBundle:Admin/Library:index }
admin_library_new:
    path:     /library/new
    defaults: { _controller: NGSContentBundle:Admin/Library:new }

admin_library_edit:
    path:     /library/{id}/edit
    defaults: { _controller: NGSContentBundle:Admin/Library:edit }

admin_library_delete:
    path:     /library/{id}/delete
    defaults: { _controller: NGSContentBundle:Admin/Library:delete }

admin_contactbook:
    path:     /contactbook
    defaults: { _controller: NGSContentBundle:Admin/Contactbook:index }
admin_contactbook_new:
    path:     /contactbook/new
    defaults: { _controller: NGSContentBundle:Admin/Contactbook:new }

admin_contactbook_edit:
    path:     /contactbook/{id}/edit
    defaults: { _controller: NGSContentBundle:Admin/Contactbook:edit }

admin_contactbook_delete:
    path:     /contactbook/{id}/delete
    defaults: { _controller: NGSContentBundle:Admin/Contactbook:delete }

admin_contactbook_section:
    path:     /contactbook-section
    defaults: { _controller: NGSContentBundle:Admin/ContactbookSection:index }
admin_contactbook_section_new:
    path:     /contactbook-section/new
    defaults: { _controller: NGSContentBundle:Admin/ContactbookSection:new }

admin_contactbook_section_edit:
    path:     /contactbook-section/{id}/edit
    defaults: { _controller: NGSContentBundle:Admin/ContactbookSection:edit }

admin_contactbook_section_delete:
    path:     /contactbook-section/{id}/delete
    defaults: { _controller: NGSContentBundle:Admin/ContactbookSection:delete }