services:

    ngs_content.admin.about:
        class: NGS\ContentBundle\Admin\AboutAdmin
        arguments: [~, NGS\ContentBundle\Entity\About, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: About}

    ngs_content.admin.home:
        class: NGS\ContentBundle\Admin\HomeAdmin
        arguments: [~, NGS\ContentBundle\Entity\Home, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Home}

    ngs_content.admin.service:
        class: NGS\ContentBundle\Admin\ServiceAdmin
        arguments: [~, NGS\ContentBundle\Entity\Service, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Service}

    ngs_content.admin.mission:
        class: NGS\ContentBundle\Admin\MissionAdmin
        arguments: [~, NGS\ContentBundle\Entity\Mission, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Mission}

    ngs_content.admin.announcement:
        class: NGS\ContentBundle\Admin\AnnouncementAdmin
        arguments: [~, NGS\ContentBundle\Entity\Announcement, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Announcement}

    ngs_content.admin.event:
        class: NGS\ContentBundle\Admin\EventAdmin
        arguments: [~, NGS\ContentBundle\Entity\Event, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Event}

    ngs_content.admin.contact_book_section:
        class: NGS\ContentBundle\Admin\ContactBookSectionAdmin
        arguments: [~, NGS\ContentBundle\Entity\ContactBookSection, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ContactBookSection}

    ngs_content.admin.contact_book:
        class: NGS\ContentBundle\Admin\ContactBookAdmin
        arguments: [~, NGS\ContentBundle\Entity\ContactBook, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ContactBook}

    ngs_content.admin.library:
        class: NGS\ContentBundle\Admin\LibraryAdmin
        arguments: [~, NGS\ContentBundle\Entity\Library, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Library}
