services:

    ngs_content.admin.about:
        class: NGS\ContentBundle\Admin\AboutAdmin
        arguments: [~, NGS\ContentBundle\Entity\About, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: About}
