services:

    ngs_content.admin.article:
        class: NGS\ContentBundle\Admin\ArticleAdmin
        arguments: [~, NGS\ContentBundle\Entity\Article, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Article}

    ngs_content.admin.announcement:
        class: NGS\ContentBundle\Admin\AnnouncementAdmin
        arguments: [~, NGS\ContentBundle\Entity\Announcement, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Announcement}

    ngs_content.admin.event:
        class: NGS\ContentBundle\Admin\EventAdmin
        arguments: [~, NGS\ContentBundle\Entity\Event, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Event}

    ngs_content.admin.contact_book_section:
        class: NGS\ContentBundle\Admin\ContactBookSectionAdmin
        arguments: [~, NGS\ContentBundle\Entity\ContactBookSection, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ContactBookSection}

    ngs_content.admin.contact_book:
        class: NGS\ContentBundle\Admin\ContactBookAdmin
        arguments: [~, NGS\ContentBundle\Entity\ContactBook, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ContactBook}

    ngs_content.admin.library:
        class: NGS\ContentBundle\Admin\LibraryAdmin
        arguments: [~, NGS\ContentBundle\Entity\Library, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Library}

    ngs_content.admin.article_type:
        class: NGS\ContentBundle\Admin\ArticleTypeAdmin
        arguments: [~, NGS\ContentBundle\Entity\ArticleType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ArticleType}
